---
- name: yum update section
  hosts: host-1
    
  tasks:
  - name: apache latest version
    ansible.builtin.yum:
        name: httpd
        state: latest
    become: true
    
  - name: ensure running
    service:
        name: httpd
        state: started
    become: true

  - name: copy file
    ansible.builtin.copy:
        src: ./index1.html
        dest: /var/www/html/index1.html
        owner: apache
        group: apache
        mode: '0644'
    become: true
  - name: yum update
    ansible.builtin.yum:
        name: '*'
        state: latest
    become: true
    
  - name: shell command
    shell: 'ls -latr'
    register: command_output
    become: true
    
  - debug:
        var: command_output.stdout_lines
        
    
        